### PR TITLE
GH-743 Fix hero content alignment and buttons in the mobile view

### PR DESCRIPTION
**Pull request by sudhinm**
This fixes the hero content alignment in the mobile view. Sign in and theme switcher button shrinking issue also have fixed.

Before
Screenshot 2021-10-05 at 11 35 41 PM

After
Screenshot 2021-10-05 at 11 36 17 PM

Issue - #743

### CODE REVIEW

**Comment by dzikoysk** [comment]
I think that padding below and above Hero component could be a little smaller and padding below image could be a little increased, what do you think about it?

**Comment by sudhinm** [comment]
> I think that padding below and above Hero component could be a little smaller. Also, padding below image could be a little increased. What do you think about it?

Sure, that would look better.

**Comment by sudhinm** [comment]
Is this ok @dzikoysk ?
Screenshot 2021-10-06 at 12 18 14 AM

**Review by dzikoysk — APPROVED** [review]

**Comment by dzikoysk** [comment]
Yeah, it's better now 👍

**Pull request merged**
