### PR TITLE
GH-1654 Implement dashboard

### PR DESCRIPTION
**Pull request by dzikoysk**
obraz

SJ PW 2022

### CODE REVIEW

**Comment by ThraaxSession** [comment]
Hi @dzikoysk wouldn't it be more accessible of the padding between resolved requests is smaller? It takes a lot of space.

**Comment by dzikoysk** [comment]
I'm going to add one more chart, so I'll probably try to reduce  its height 🤔

**Comment by dzikoysk** [comment]
@ThraaxSession 

obraz

What do you think?

**Comment by dzikoysk** [comment]
Nice :)

**Comment by dzikoysk** [comment]
Thanks 💜 Yeah, I think it might be a good idea to release a next version with those charts.

**Pull request merged**
