### PR TITLE
GH-2251 Fix Jetty Metrics Recording

### PR DESCRIPTION
**Pull request by solonovamax**
Hopefully this uncooks the jetty metrics

Also bumps the version for prometheus metrics.

### CODE REVIEW

**Comment by dzikoysk** [comment]
> Hopefully

Did you try to run this? :sweat_smile:

**Comment by solonovamax** [comment]
> > Hopefully
> 
> Did you try to run this? 😅

you never know, some magic issue might pop up later

**Comment by solonovamax** [comment]
actually I think I did something dumb, is there an easy way to take an arbitrary string and normalize it as a url path?

eg.

`//metrics///` -> `/metrics`?
I couldn't find any from a quick look earlier

**Comment by dzikoysk** [comment]
You could try with our `Location` class I think, it's intended to clean up messed paths _(in general)_

**Review by dzikoysk — APPROVED** [review]

**Comment by dzikoysk** [comment]
Thanks, let's see how it'll work :shipit:

**Pull request merged**
