### PR TITLE
GH-956 allow versions to be filtered

### PR DESCRIPTION
**Pull request by WithoutAName25**
If you have something that should be implemented differently just write me. It might be also useful to add a filter to show only `alpha`, `beta` or `release` versions, but I think that should be in a second pull request if we want to implement this.

### CODE REVIEW

**Comment by dzikoysk** [comment]
Thanks for PR! ❤️ 

I think that if we want to provide filter for prefix & suffix, we should implement this here as it's a part of API and we should not modify it in the future if possible. What do your think about regex? 🤔

**Comment by WithoutAName25** [comment]
I thought regex would be to difficult to use and it would be easier to do sth like `?filter=2.0&type=release` to get all versions that start with `2.0` and are releases and not betas or alphas.
And with regex you maybe have to encode / escape some special characters. But if we implement a feature in the frontend where you can generate badge urls (at some point in the future), regex might be the better option.
But it would be no problem to switch to regex, I would have to edit just one line of code.

**Comment by WithoutAName25** [comment]
As reference:
https://shields.io/maven-metadata/v?metadataUrl=https%3A%2F%2Frepo1.maven.org%2Fmaven2%2Fcom%2Fgoogle%2Fguava%2Fguava%2Fmaven-metadata.xml&versionPrefix=29.&versionSuffix=-android
That's how shields.io implemented this

**Review by dzikoysk — APPROVED** [review]

**Comment by dzikoysk** [comment]
Makes sense, the PR also looks good! Let's merge it.

**Pull request merged**
