### PR TITLE
GH-1738 Add Arch Linux install instructions

### PR DESCRIPTION
**Pull request by PolarianDev**
For a while now there has been an AUR package for reposilite, to aid in the installing on Arch (and arch based distributions).

I have added the basic installation from the AUR (without an AUR helper) however I have also left a link to the Arch Wiki which has a lot of information on the installation process on Arch Linux.

As for me, I am the co-maintainer of the AUR package, and I am the maintainer of the reposilite ArchWiki page, so any issues with it please let me know.

Any issues with the AUR package can be submitted on the repository here: https://onedev.polarian.dev/polarrepo/reposilite

You can also install reposilite directly, already packaged, from PolarRepo (an unofficial arch repository which I maintain to aid in installation of AUR packages I maintain), for more information check this link: https://onedev.polarian.dev/polarrepo/~files

Good luck with the development of Reposilite :)

### CODE REVIEW

**Comment by dzikoysk** [comment]
Hi, good to know there's such distribution channel! :) Unfortunately I can't list it as the official one as it's not controlled by me. As you can see, we're listing only the official channels, because it guarantees it's distributed in its original form - as an example, below your change in readme there's a Helm chart. It was requested by @joshuasing and he helped me with setup, so it fully goes through our infrastructure now:

* https://github.com/reposilite-playground/reposilite-helm
* https://helm.reposilite.com/
* https://artifacthub.io/packages/helm/reposilite/reposilite

If you'd like to make it official, we should do sth like that for AUR as well.

**Comment by PolarianDev** [comment]
@dzikoysk I am a little confused here.

I understand you can not list "unofficial" solutions, but I am unsure about the links you have provided above and how that made it official. You are free to be added as a maintainer for the package as well on all repositories. If you want prebuilt packages provided for arch linux under the reposilite domain I can help you set that up to (all it needs is an nginx server and a build server, but the build part might be fiddly).

However a TU in the future might want to move the package into the community repository which would mean it could be directly pulled (without additional configuration) by any arch linux installation.

Its always better to work with the developer to find the best "official" support possible, well in my opinion. I am only a co-maintainer and do not have full permissions, so I would also need to ask the maintainer.

Could you list what you would want to satisfy an "official" support?

**Comment by PolarianDev** [comment]
[Packaging status](https://repology.org/project/reposilite/versions)

**Comment by PolarianDev** [comment]
Seems the AUR is the only package available across the linux ecosystem, little unfortunate considering reposilite has quite a large reputation now (I have seen it grow over the last 2-3 ish years)

**Comment by dzikoysk** [comment]
Oh, those links were just an example of what I mean by official distribution with a community support and that we can set it up just in case :) To be fair I don't know much about distributing packages for any Linux distribution, but I guess it'd be nice to have it if that's indeed preferred approach for some users.

By "official" I mean that all sources are located within Reposilite repository/organization and it's fully/partly automated process associated with our release lifecycle. Those builds should be also distributed from my account or a special account associated with our CI. Could you describe this process & list necessary steps to publish such package and how do you think it should work?

**Comment by PolarianDev** [comment]
Alright Arch Linux is different than other distributions but let me describe the process.

The AUR (Arch User Repository) is basically a dumping ground of PKGBUILDs which are not supported by the Arch TUs, they can be high quality and worthy of being included (but not popular or not have a TU interested in supporting it) or they could be total rubbish which barely builds or installs to the wrong paths on the system.

All the PKGBUILDs I maintain I get reviewed, and keep to a high quality, however I am a co-maintainer for reposilite and thus its not my package. I keep all the packages I maintain on https://onedev.polarian.dev/polarrepo this is non-negotiable, however I am happy to have it mirrored from the reposilite organisation, but it also must be under my namespace as I am a co-maintainer.

The AUR distributes lets call them "schematics" on how to build the packages, you clone and build them manually, for most users this is a pain, so we have repositories like other distributions which distribute the software, which is what the TUs do, draw high quality and high used AUR packages into the community repository to be built by the arch linux deployment servers, this you can not control but they are very capable people.

Currently the package is just in the AUR, this is good if you want control as you can get Arch Users to pull the builds from your own servers under your organisation, provided you got a basic http server lying around ready to serve the packages.

When it comes to AUR, you literally just maintain the source files, which can be found here: https://aur.archlinux.org/cgit/aur.git/tree/?h=reposilite (AUR) and here: https://onedev.polarian.dev/polarrepo/reposilite (My production onedev instance). When you update the package, as long as the installation has not changed, you bump the version of the PKGBUILD regenerate the .SRCINFO and then push it to the AUR to update (this can be automated, but is generally unadvised as you should test the package before pushing to AUR).

If you want to provide your own repository to pull the builds from, this is quite a bit harder as you need the following:
- A build server which will build the packages (must be arch linux based)
- A http endpoint to serve the repository
- A gpg key to sign the packages to ensure people are installing trusted packages (people will have to manually trust the gpg key as it will not be distributed with the arch keychain as only TUs get that privilege)

I already build and distribute reposilite under PolarRepo to make it easy to install, and thus have experience with this already, you can browse what the repository looks like here: https://polarrepo.polarian.dev

This repository is added to a users pacman configuration (the arch linux package manager) like any other distribution and then reposilite can be pulled like any other package, it will be installed to clean and relavent paths, and includes a user for privilege separation and its own systemd task, this makes it easier to setup and install than a source install, and a strong alternative to people who hate docker (people like me), and also people who use LXC containers (people like me) or people who want reposilite running bare metal.

I hope I have explained this well enough for you to understand!

**Comment by dzikoysk** [comment]
Thanks :) Ok, so it basically does the same thing what Dockerfile + entrypoint.sh. It's hosted as Git repository on AUR:

1. Main repository: https://aur.archlinux.org/reposilite.git/
2. Your "fork" to sync sources: https://onedev.polarian.dev/polarrepo/reposilite/~files/master
3. PKGBUILD contains main install script: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=reposilite
4. Some extra scripts to properly setup extra things like e.g. systemd integration

And that's basically it, when user installs it, it's just pulling those sources out and it builds whole app locally. Those scripts looks kinda complicated and it's not really my thing to play with it for now, so I guess it's good that it's maintained by someone who's using this ecosystem daily. Having that in mind, I think that we could just mirror that repository as you said to e.g. `reposilite-playground/reposilite-aur` repository and I think that's all, regular user can pull this from official repository and it doesn't go through any private instance by default. I also think that instead of listing this in readme (it's still kinda a niche and just one distro), I'd probably create `Arch` guide in `Installation` section.

**Comment by PolarianDev** [comment]
> Your "fork" to sync sources: https://onedev.polarian.dev/polarrepo/reposilite/~files/master

Not exactly, you can also push directly to the AUR without a second git repository, I use a second git repository which supports PR and issues for better management of issues and to allow others to submit PR to fix issues, this is not possible using the AUR git repository and interface.

> And that's basically it, when user installs it, it's just pulling those sources out and it builds whole app locally, right? Because custom repository with our own builds sounds like an optional step to just speedup installation process.

A user must pull the repository using git, and then when they have they must use `makepkg` which will fetch the sources, and compress it into the package format, this will pop out the package which can then be installed. Custom repositories is indeed an additional step which will cut out the overhead of building the package manually (and the issues the user could encounter link not having the right build environment setup), also one issue with this approach is users will need to pull the changes every single time the package is updated, and rebuild it, thus a repository means they can run the typical `pacman -Syu` command which updates the system, but also pull from the custom repository and update without ever needing to worry about the build process.

> Those scripts looks kinda complicated and it's not really my thing to play with it for now, so I guess it's good that it's maintained by someone who's using this ecosystem daily. Having that in mind, I think that we could just mirror that repository as you said to e.g. reposilite-playground/reposilite-aur repository and I think that's all, regular user can pull this from official repository and it doesn't go through any private instance by default. I also think that instead of listing this in readme (it's still kinda a niche and just one distro), I'd probably create Arch guide in Installation section.

Sounds like a good idea to me, for other distributions it normally falls down to the individual to support it, ubuntu/debian requitres you setting up your own ppa for example.

As a whole arch has a lot nicer support for packaging of more software and extending its outreach, and a lot of distributions use arch, manjaro has the `pamac` AUR helper which will be able to pull reposilite directly from the AUR and build it.

Most ubuntu users are docker users anyways, so I doubt worrying about ubuntu will do much :P

**Comment by PolarianDev** [comment]
Reposilite will remain in my repository unless you want a repo under your namespace for ownership purposes, but that is completely optional :)

If you are wondering what the update.sh script does which is in the repository, its a script charles wrote to automatically create PRs every time you push a new release, see: https://onedev.polarian.dev/polarrepo/reposilite/~pulls/3

**Comment by PolarianDev** [comment]
I want to create a CI/CD task to automatically build the package (and maybe even push to AUR) when merged into master, this means I can then pull the built package and sign it and then stick it on my repository, or people could download the package directly from the releases section of the AUR repository if they do not want to use the repository or build it themselves.

**Comment by dzikoysk** [comment]
> Not exactly, you can also push directly to the AUR without a second git repository [...]

Yeah, that's why I said "fork" as the default AUR repo is basically just git repo container without any fancy stuff 😛 

> Custom repositories is indeed an additional step which will cut out the overhead of building the package manually

To be fair, we could probably simply download final JAR from the official Maven repository. It's tested on our CI against various targets, so in general it should be enough and we'd skip the most painful part.

> Most ubuntu users are docker users anyways, so I doubt worrying about ubuntu will do much :P

Yeah, Docker is probably the most popular distribution target as it works ootb everywhere. I don't want to add extra targets without a specific request on our tracker, so we don't have to worry about it atm.

> Reposilite will remain in my repository unless you want a repo under your namespace for ownership purposes, but that is completely optional :)

The best solution for me would be to move whole repository/process to GitHub, even tho I clearly see you don't like it 😅. It's the main platform for each project associated with Reposilite and there's also a whole ecosystem around hooks & ci. It's also easier to find community here, because there's no need to create standalone account on 3rd-party, self-hosted instance etc.

**Comment by PolarianDev** [comment]
> To be fair, we could probably simply download final JAR from the official Maven repository. It's tested on our CI against various targets, so in general it should be enough and we'd skip the most painful part.

That is unconventional unless it is a -bin package (binary package), which it is not :)

> Yeah, Docker is probably the most popular distribution target as it works ootb everywhere. I don't want to add extra targets without a specific request on our tracker, so we don't have to worry about it atm.

Well for arch you got support from two people (one of them is me), other targets you got no support which means it would fall down to yo solely, which would waste time which could be used developing reposilite.

> The best solution for me would be to move whole repository/process to GitHub, even tho I clearly see you don't like it sweat_smile. It's the main platform for each project associated with Reposilite and there's also a whole ecosystem around hooks & ci. It's also easier to find community here, because there's no need to create standalone account on 3rd-party, self-hosted instance etc.

You are encouraging someone who takes privacy and self hosting very seriously to centralise a large portion on what he works on. Yes it is slightly annoying having it on another instance, but if I move reposilite I would need to move all the AUR packages, they are are sorted under one namespace for a reason, and hence non-negotiable. (it either makes it more annoying for you, or for me, and I am selfish :P)

**Comment by dzikoysk** [comment]
> That is unconventional unless it is a -bin package (binary package), which it is not :)

I was talking about `.jar` as it's just literally the same file that's produced by `shadowJar` task. As far as I see, you're not launching tests during build, so the result is basically the same I guess.

> You are encouraging someone who takes privacy and self hosting very seriously to centralise a large portion on what he works on. 

Well, to be fair I'm talking only about the `reposilite` package and that's all. I don't think there would be a need to move anything else to be fair, it's sounds a little bit off that you'd have to move unrelated packages 🤔 Anyway, if you don't want to/can't move to GitHub then I cannot brand this distribution channel as official, but that's basically it. I guess we could still add AUR guide to the reposilite-site, we'll just need to some kind of a note at the top of the page that it is not official distribution channel and it's up to AUR community to maintain & guarantee safety of this package or sth like that.

**Comment by PolarianDev** [comment]
> I was talking about .jar as it's just literally the same file that's produced by shadowJar task that you use in pkgbuild. As far as I see, you're not launching tests during build, so the result is basically the same I guess.

It technically is, but there is 3 different package types:

normal type: build the latest tagged release
-git packages: clone the repository and compile the latest commit
-bin packages: install a distributed binary from upstream

**Comment by PolarianDev** [comment]
> Well, to be fair I'm talking only about the reposilite package and that's all. I don't think there would be a need to move anything else to be fair, it's sounds a little bit off that you'd have to move unrelated packages thinking Anyway, if you don't want to/can't move to GitHub then I cannot brand this distribution channel as official, but that's basically it. I guess we could still add AUR guide to the reposilite-site, we'll just need to some kind of a note at the top of the page that it is not official distribution channel and it's up to AUR community to maintain & guarantee safety of this package or sth like that.

The thing is the reposilite package is related to all the other packages because it is a AUR package, so moving reposilite will then mean its no longer sorted with the other AUR packages, which then makes things confusing for me :)

create a repository and give me write access to it for the repository and I will push the package to github too, but my version remains as well, for sorting reasons :)

**Comment by PolarianDev** [comment]
@dzikoysk Could you create reposilite-aur here: https://github.com/reposilite-playground

And then give me permissions to push to the repository :)

**Comment by PolarianDev** [comment]
Yes, @dzikoysk do not forget Charles as well, as he is the Maintainer.

I have set up a rule on my repository to push any changes made there directly to github.

I assume you want all issues on github?

**Comment by dzikoysk** [comment]
> Yes, @dzikoysk do not forget Charles as well, as he is the Maintainer.

Done :)

> I assume you want all issues on github?

I don't mind if you prefer to communicate on your instance by default, but I'll keep issues section open on GitHub so gh users will have a possibility to communicate & contribute here.

**Comment by PolarianDev** [comment]
All my AUR packages inherit from the polarrepo group rules, hence the reason I keep them all under a namespace :)

Besides it does not matter too much because I have notifications on both.

**Comment by PolarianDev** [comment]
Welp that works both ways now... github users are still free to open issues. I do want to point out something though:

image

Always can use github sso, but I understand you want it under your namespace :)

**Comment by dzikoysk** [comment]
Nice :) My main goal was to not block `Issues` section as some repos/orgs do, and enforce e.g. Jira instead. It always makes me sick.

**Comment by PolarianDev** [comment]
Understandable.

If you are happy with it now, then thats good, I am happy to check both github and onedev because I use both of them

**Comment by dzikoysk** [comment]
I think we should go for the option I've proposed above:

> I also think that instead of listing this in readme (it's still kinda a niche and just one distro), I'd probably create Arch guide in Installation section.

Would you like to write a guide about that? 

> I do feel I should start publishing the built packages on the github releases to, this will allow users to pull the release directly from github too, allowing them to install directly from github releases, would you be interested in that?

Sounds like a good idea :)

**Comment by PolarianDev** [comment]
> I think we should go for the option I've proposed above:
> 
> > I also think that instead of listing this in readme (it's still kinda a niche and just one distro), I'd probably create Arch guide in Installation section.

Ah sorry, I missed this.

I can push a new commit with this, do you want the install guide within the README below the regular installation guide or do you desire it in another way?

> Would you like to write a guide about that?

Sure, if you make it clear what you want :)

> > I do feel I should start publishing the built packages on the github releases to, this will allow users to pull the release directly from github too, allowing them to install directly from github releases, would you be interested in that?
> 
> Sounds like a good idea :)

Already done the first release, it also identified a potential bug with onedev, which helps the onedev developer as well, seems like two projects benefit today haha

**Comment by dzikoysk** [comment]
By the guide, I mean an article in `Installation` section on our site :) I'd probably write a complete instruction on how to pull this package, configure and run on Arch, just like e.g. Docker guide:

* https://reposilite.com/guide/docker

Sources: https://github.com/dzikoysk/reposilite/tree/main/reposilite-site/data/guides/installation

**Comment by PolarianDev** [comment]
Ah, so it is just markdown right?

What do you use to generate the site?
-- 
Polarian
GPG signature: 0770E5312238C760
Website: https://polarian.dev
JID/XMPP: ***@***.***

**Comment by dzikoysk** [comment]
The site will be automatically generated and deployed. For development, you can start it with `npm run dev`.

**Comment by PolarianDev** [comment]
Good to know.

I was more interested in what software you use the build the software, 
is it a documentation project such as docusaurus? or is it custom coded 
by you?
-- 
Polarian
GPG signature: 0770E5312238C760
Website: https://polarian.dev
JID/XMPP: ***@***.***

**Comment by dzikoysk** [comment]
It's just a regular Next.js app with SSG target hosted on Vercel :)

**Comment by PolarianDev** [comment]
Ah...

I do not get why people use Vercel, every Vercel site I know of does not 
support IPv6.

Checking yours it seems you do:

```
❯ dig AAAA reposilite.com

; <<>> DiG 9.18.13 <<>> AAAA reposilite.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37988
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;reposilite.com.                        IN      AAAA

;; ANSWER SECTION:
reposilite.com.         282     IN      AAAA    2606:4700:3031::ac43:8ef6
reposilite.com.         282     IN      AAAA    2606:4700:3037::6815:1b99

;; Query time: 0 msec
;; SERVER: 2001:8b0:57a:2385::1#53(2001:8b0:57a:2385::1) (UDP)
;; WHEN: Mon Apr 03 23:05:16 BST 2023
;; MSG SIZE  rcvd: 99
```

Probably means nothing to you, but it means a lot for me, so thank you 
for bothering adding the AAAA record :)

I will update the PR tonight writing up a page for Arch Linux, you can 
review it then :)

Thanks for providing all the information needed (and satisfying my 
curiosity).
-- 
Polarian
GPG signature: 0770E5312238C760
Website: https://polarian.dev
JID/XMPP: ***@***.***

**Comment by PolarianDev** [comment]
^^^ I fixed a whitespace inconsistency in that commit too... it was inconsistent and was annoying me xD

**Review by dzikoysk — APPROVED** [review]

**Comment by dzikoysk** [comment]
Sorry for late response, I'm slightly busy lately. The guide looks fine to me :)

**Pull request merged**
