### PR TITLE
GH-1011 Add Pac4J auth.

### PR DESCRIPTION
**Pull request by EthanDevelops**
#1011

### CODE REVIEW

**Comment by dzikoysk** [comment]
Btw I'm not sure if we want to use this Javalin extension, it's mostly about authenticating request using `before` handler and we should probably handle it through `AuthenticationFacade` manually to avoid this kind of `before` -> `get` flow 🤔

**Comment by EthanDevelops** [comment]
We could adapt the core library to the current auth system.

**Comment by EthanDevelops** [comment]
Tags request:
dependencies, security, and java

**Comment by dzikoysk** [comment]
In most cases we don't tag PRs, it's the responsibility of issue to properly address conversation. I'll add security tag tho :)

**Comment by dzikoysk** [comment]
#1032 can affect this also

**Comment by dzikoysk** [comment]
Hey @EthanDevelops, what's the status of this PR? :)

**Comment by EthanDevelops** [comment]
Hey! It’s a bit stale at the moment because I think that the current auth implementation would be pretty hard to make work with Pac4j. Maybe the auth for the website could use some sort of OAuth system that would be verified in the backend. Maybe an API key solution could work?

**Comment by dzikoysk** [comment]
Not sure how it works yet, I guess that this feature might be breaking as I thought, so we need to take care of this before release of stable 3.x. I'll try to read some pac4j docs this week.

**Pull request closed without merging**
